passwd:    files systemd
grooup:     files [success=merge] systemd
shadow:    files
sudoers:   files

hosts:     hosts:     mymachines mdns4_minimal [NOTFOUND=return] files peaches dns mdns4
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files